apps/cms/urls.py
from django.urls import path
from . import views,views_of_course,views_of_staff
from django.conf.urls.static import static
from django.conf import settings
app_name = 'cms'
urlpatterns = [
    path('home',views.home,name = 'home'),
    path('news_release',views.news_release,name = 'news_release'),
    path('release_news',views.ReleaseNews.as_view(),name = 'release_news'),
    path('category',views.category,name = 'category'),
    path('image_upload_to_local',views.image_upload_to_local,name = 'image_upload_to_local'),
    path('category_modify',views.category_modify,name = 'category_modify'),
    path('category_delete',views.category_delete,name = 'category_delete'),
    path('thumbnail_process',views.thumbnail_process,name = 'thumbnail_process'),
    path('banner_control',views.banner_control,name = 'banner_control'),
    path('banner_cms_manager_get', views.banner_cms_manager_get, name='banner_cms_manager_get'),
    path('banner_cms_manager_add', views.banner_cms_manager_add, name='banner_cms_manager_add'),
    path('banner_cms_manager_edit', views.banner_cms_manager_edit, name='banner_cms_manager_edit'),
    path('banner_cms_manager_delete', views.banner_cms_manager_delete, name='banner_cms_manager_delete'),
    path('lover_mumu', views.lover_mumu, name='lover_mumu'),
    path('Discover_Process', views.Discover_Process, name='Discover_Process'),
    path('demo_cms_address_ip', views.demo_cms_address_ip, name='demo_cms_address_ip'),
    path('demo_cms_manager_client', views.demo_cms_manager_client, name='demo_cms_manager_client'),
    path('demo_cms_delete_ip', views.demo_cms_delete_ip, name='demo_cms_delete_ip'),
    path('news_preview_cms_all', views.News_preview_cms_all.as_view(), name='news_preview_cms_all'),
    path('news_preview_cms_edit', views.news_preview_cms_edit, name='news_preview_cms_edit'),
    path('news_preview_cms_delete', views.news_preview_cms_delete, name='news_preview_cms_delete'),
]+static(settings.CLIENTIMAGE_ROOT,document_root = settings.CLIENTIMAGE_ROOT)


urlpatterns += [
    path('course_cms_add',views_of_course.PublishCourse.as_view(),name='course_cms_add'),
    path('write_cms_add',views_of_course.write_cms_add,name='write_cms_add'),
]


#管理员
urlpatterns += [
    path('staff',views_of_staff.staff,name='staff'),
    path('StaffAdd',views_of_staff.StaffAdd.as_view(),name='StaffAdd'),
]

apps/news/urls.py
from django.urls import path
from .import views

app_name = 'news'
urlpatterns = [
    path('index',views.index,name='index'),
    path('news_list',views.news_list,name='news_list'),
    path('news_detail/<int:news_id>',views.news_detail,name='news_detail'),
    path('news_comment',views.news_comment,name='news_comment'),

]

xfz02/urls.py
from django.contrib import admin
from django.urls import path,include
from apps.news import views
from apps.legend import views as views_legend
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/',include('apps.news.urls')),
    path('',views.index,name='index'),
    path('cms/',include('apps.cms.urls')),
    path('register/',include('apps.register.urls')),
    path('course/',include('apps.course.urls')),
    path('pay/',include('apps.payinfo.urls')),
    path('search/',include('apps.search.urls')),
    path('ueditor/',include('apps.ueditor.urls')),
    path('party/',include('apps.party.urls')),
    path('legend',views_legend.index),
    path('legend',include('apps.legend.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

apps/cms/models.py
from django.db import models

# Create your models here.

class Address(models.Model):
    ip = models.CharField(max_length=20)
    content = models.CharField(max_length=20,default='null')
    country = models.CharField(max_length=10,default='null')
    province = models.CharField(max_length=10,default='null')
    city = models.CharField(max_length=10,default='null')
    isp = models.CharField(max_length=10,default='null')
    pub_time = models.DateTimeField(auto_now_add='null')
    class Meta:
        ordering =['-pub_time']

apps/news/models.py
from django.db import models

# Create your models here.
class News(models.Model):
    title = models.CharField(max_length = 200)
    thumbnail = models.URLField()
    content = models.TextField()
    category = models.ForeignKey('Category',on_delete=models.SET_NULL,null=True)
    pub_time = models.DateTimeField(auto_now_add = True)
    author = models.ForeignKey('register.User',on_delete=models.SET_NULL,null= True)
    class Meta:
        ordering = ['-pub_time']

class Category(models.Model):
    name = models.CharField(max_length = 20)
    pub_time2 = models.DateTimeField(auto_now_add=True,null=True)


class Discover(models.Model):
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('register.User',on_delete=models.SET_NULL,null=True)

class NewsComment(models.Model):
    news = models.ForeignKey('News',on_delete=models.CASCADE,null=True,related_name='newscomment')
    comment = models.TextField(max_length=200)
    pub_time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('register.User',on_delete=models.SET_NULL,null=True)
    class Meta:
        ordering = ['-pub_time']


class Banner(models.Model):
    link_to = models.CharField(max_length=300)
    priority = models.IntegerField()
    image_url = models.URLField()
    pub_time = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-priority']

apps/cms/forms.py
from django import forms
from utils.restful import FormError
from utils import restful
from apps.course.models import Course
from apps.news.models import News,Banner


class NewsForm(forms.ModelForm,FormError):
    category = forms.IntegerField()
    class Meta:
        model = News
        fields = ('title','content','thumbnail')



class CategoryForm(forms.Form,FormError):
    id = forms.CharField(max_length=20,required=False)
    name = forms.CharField(max_length=30)


class BannerForm(forms.ModelForm,FormError):
    banner_id = forms.IntegerField(required=False)
    class Meta:
        model = Banner
        fields = '__all__'

class PubCourseForm(forms.ModelForm,FormError):
    category_id = forms.IntegerField()
    teacher_id = forms.IntegerField()
    class Meta:
        model = Course
        exclude = ("category",'teacher')

apps/cms/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View
from utils import restful
from .forms import CategoryForm,NewsForm,BannerForm
from apps.news.models import Category,Banner,News,Discover
import os,time
from django.conf import settings
from qiniu import Auth as qiniuAuth
from apps.news.serializers import BannerSerializers
from apps.news.forms import DiscoverForm
from apps.register.models import User
from .models import Address
from django.utils.timezone import make_aware
from datetime import datetime
from django.core.paginator import Paginator
from urllib import parse

#权限访问装饰器
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required
from django.contrib.admin.views.decorators import staff_member_required

# Create your views here.
def home(request):
    return render(request, 'cms/news/home.html')


@staff_member_required(login_url='index')
def news_release(request):
    return render(request,'cms/news/release.html')


#发布新闻
@method_decorator(permission_required(perm='news.add_news',login_url='/'),name='dispatch')
class ReleaseNews(View):
    def get(self,request):
        category = Category.objects.all()
        context = {'category':category}
        return render(request,'cms/news/release.html',context=context)
    def post(self,request):
        print('到post这了')
        form = NewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            print('content',content)
            category_id = form.cleaned_data.get('category')
            category = Category.objects.get(id = category_id)
            print('category_id',category_id)
            thumbnail = form.cleaned_data.get('thumbnail')
            author = request.user
            new = News.objects.create(title=title,content=content,category=category,thumbnail=thumbnail,author=author)
            new.save()
            print('OK')
            return restful.ok()
        print('表单错')
        print('form.get_errors',form.get_errors)
        return restful.params_error(message='表单提交有问题')
#标签


def category(request):
    if request.method == 'GET':
        categorys = Category.objects.prefetch_related('news_set').all().order_by("-id")
        content = {'categorys':categorys}
        return render(request,'cms/news/category.html',context=content)
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            print('name',name)
            category = Category.objects.create(name=name)
            category.save()
            return restful.result(message='添加成功')
        return restful.params_error('表单验证错误')


def image_upload_to_local(request):
    file = request.FILES.get('file')
    file_name = file.name.split('.')[1]
    file_name = str(int(time.time()*1000))+ '.' +file_name
    with open((os.path.join(settings.CLIENTIMAGE_ROOT,file_name)),'wb') as f:
        for chunk in file.chunks():
            f.write(chunk)
    url = request.build_absolute_uri(settings.STATIC_URL+'client_image/'+file_name)
    print(url)
    return restful.result(data={'url':url})

@method_decorator(permission_required(perm='category.change_category',login_url='/'),name='dispatch')
def category_modify(request):
    form = CategoryForm(request.POST)
    if form.is_valid():
        id = form.cleaned_data.get('id')
        print('category_id',id)
        name = form.cleaned_data.get('name')
        print('category_name',name)
        try:
            Category.objects.filter(pk=id).update(name=name)
            return restful.ok()
        except:
            return restful.params_error('该分类不存在')

    else:
        return restful.params_error(message=form.get_error())

@method_decorator(permission_required(perm='category.delete_category',login_url='/'),name='dispatch')
def category_delete(request):
    id = request.POST.get('id')
    print('id',id)
    if id:
        try:
            dele = Category.objects.filter(id=id).delete()
            print('dele',dele)
            return restful.ok()
        except:
            return  restful.params_error(message='数据库无法查到这个ID，请刷新')
    else:
        return restful.params_error(message='没有这个名称，无法删除，请刷新')


def thumbnail_process(request):
    access_key = 'L7Idi7_0oH-8LC1g2CjLb1h9Z6kN4-JLoqoOn21U'
    secret_key = 'IGhDFYcbCns_3RcEopOwmHLE8M7XctIe_bVwYfHr'
    bucket = 'establish'
    q = qiniuAuth(access_key,secret_key)
    token = q.upload_token(bucket)
    return restful.result(data={'token':token})

def banner_control(request):
    return render(request,'cms/banner/banner.html')


#管理banner
def banner_cms_manager_get(request):
    banner = Banner.objects.all()
    serializer = BannerSerializers(banner,many=True).data
    context = {'banners':serializer}
    return restful.result(data=context)

#添加banner

def banner_cms_manager_add(request):
    form = BannerForm(request.POST)
    if form.is_valid():
        link_to = form.cleaned_data.get('link_to')
        priority = form.cleaned_data.get('priority')
        image_url = form.cleaned_data.get('image_url')
        banner = Banner.objects.create(link_to=link_to,priority=priority,image_url=image_url)
        banner.save()
        return restful.result(data={'banner_id':banner.id})
    else:
        return restful.params_error(form.get_errors())

#删除banner
def banner_cms_manager_delete(request):
    banner_id = request.POST.get('banner_id')
    print('banner_id_POST',banner_id)
    banner_id_get = request.GET.get('banner_id')
    print('banner_id_GET',banner_id_get)
    try:
        banner = Banner.objects.get(id=banner_id).delete()
        return restful.ok()
    except:
        return  restful.params_error(message='没有这条数据,请刷新')


#编辑banner
def banner_cms_manager_edit(request):
    form = BannerForm(request.POST)
    if form.is_valid():
        link_to = form.cleaned_data.get('link_to')
        priority = form.cleaned_data.get('priority')
        image_url = form.cleaned_data.get('image_url')
        banner_id = form.cleaned_data.get('banner_id')
        banner = Banner.objects.filter(id=banner_id)
        banner.update(link_to=link_to,priority=priority,image_url=image_url)
        return restful.ok()
    else:
        return restful.params_error(message=form.get_errors())



#慕慕
def lover_mumu(request):
    restful.get_address_by_138ip(request,'慕慕blog访问')
    return render(request,'cms/banner/mumu.html')


#主页留言版
def Discover_Process(request):
    count = settings.PAGE_LOAD_NUM
    if request.method == 'GET':
        pp = restful.get_address_by_138ip(request=request)
        print(pp)
        discover = Discover.objects.all().select_related('author')
        context = {'discover': discover}
        return render(request, 'news/discover.html', context)
    else:
        form = DiscoverForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data.get('content')
            if str(request.user) != 'AnonymousUser':
                author = request.user
            else:
                exist = User.objects.filter(username='还未注册用户1').exists()
                if exist:
                    author = User.objects.get(username='还未注册用户1')
                else:
                    author = User.objects.create_user(username='还未注册用户1', password=12341234, telephone=13005611199,
                                                      is_staff=0)
            disc = Discover.objects.create(content=content, author=author)
            disc.save()
            return restful.ok()
        else:
            return restful.params_error('内容或标题不能为空')

#渲染IP页面
def demo_cms_address_ip(request):
    address = Address.objects.all()
    return render(request,'cms/demo/address.html',context={'addresses':address})


#查用户
def demo_cms_manager_client(request):
    user = User.objects.all()
    return render(request,'cms/demo/user_manager.html',context={'users':user})

#删除IP
def demo_cms_delete_ip(request):
    pk = request.POST.get('pk')
    try:
        Address.objects.get(pk=pk).delete()
        return restful.ok()
    except :
        return restful.params_error('未查到该id')

#新闻列表遍历
class News_preview_cms_all(View):
    def get(self,request):
        start = request.GET.get('start')
        end = request.GET.get('end')
        category = int(request.GET.get('category',0) or 0)
        title = request.GET.get('news-title')
        content = request.GET.get('news-content')
        p_for_web = request.GET.get('p_for_web',1)
        print('start',start)
        print('end',end)
        print('title', title)
        print('content', content)
        print('category', category)

        newses = News.objects.select_related('category','author').all()

        if start or end:
            if start:
                try :
                    start = make_aware(datetime.strptime(start, '%Y/%m/%d'))
                    print('start', start)
                except ValueError :
                    start = start
            else:
                start = datetime(year=2019, month=5, day=1)
                print('start', start)
            if end:
                try:
                    end = make_aware(datetime.strptime(end, '%Y/%m/%d'))
                except ValueError :
                    end = end
            else:
                end = datetime.now()
                print('end', end)
            newses = newses.filter(pub_time__range=(start, end))
        if category:
            newses = newses.filter(category=category)
        if title:
            newses = newses.filter(title__icontains=title)
        if content:
            newses = newses.filter(content__icontains=content)

        #&start=20121111&start=20121112
        urlencode = '&' + parse.urlencode({'start': start or '',
                                           'end': end or '',

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}首页{% endblock title %} |  后台管理</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminLTE/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminLTE/dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <!-- alertBox提示 -->
    <link rel="stylesheet" href="{% static 'css/sweetalert/sweetalert.css' %}">
    <script src="{% static 'css/sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/alert.js' %}"></script>

  <!-- 手写的 -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    {% block style %}{% endblock style %}
    <style>
        .nav-item{
            margin-left:20px;
        }
    </style>
</head>
<body class="sidebar-mini" style="height:auto">
    <div class="wrapper">
        <!--中上导航-->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="nav-link" data-widget="pushmenu">
                        <i class="fas fa-bars"></i>
                    </a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'news:index' %}" class="nav-link">返回网站</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">联系</a>
                </li>
            </ul>
            <form action="#" class="form-inline ml-3">
                <div class="input-group input-group-sm">
                    <input type="search" class="form-control form-control-navbar" placeholder="搜索" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                    </button>
                </div>
                </div>
            </form>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="#" class="nav-link" data-widget="control-sidebar" data-slide="true">
                        <i class="fa fa-th-large"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!--左导航-->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <a href="#" class="brand-link">
                <img src="{% static 'adminLTE/dist/img/AdminLTELogo.png' %}" alt="picture logo" class="brand-image img-circle elevation-3" style="opacity:.8">
                <span class="brand-text font-weight-light">后台管理</span>
            </a>
            <div class="sidebar">
                <div class="user-panel mt-3 pd-3 mb-3 d-flex">
                    <div class="image">
                        <img src='{% static 'images/head protrait.jpg' %}' alt="user-img" class="img-circle elevation-2">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block ">laozhu</a>
                    </div>
                </div>
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a href="{% url 'cms:home' %}" class="nav-link">
                                <i class="nav-icon fas fa-tree"></i>
                                <p>主页</p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
{#                            {% if perms.new.add_newscomment %}#}
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-th"></i>
                                    <p>新闻管理
                                        <i class="right fa fa-angle-left"></i></p>
                                </a>
                                    <ul class="nav nav-treeview" style="display:block">
                                        <li class="nav-item">
                                            <a href="{% url 'cms:release_news' %}" class="nav-link">
                                                <i class="fa fa-copy nav-icon"></i>
                                                <p>新闻发布</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="{% url 'cms:category' %}" class="nav-link">
                                                <i class="fa fa-copy nav-icon"></i>
                                                <p>新闻标签管理</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="{% url 'cms:banner_control' %}" class="nav-link">
                                                <i class="fa fa-copy nav-icon"></i>
                                                <p>Banner管理</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="{% url 'cms:news_preview_cms_all' %}" class="nav-link">
                                                <i class="fa fa-copy nav-icon"></i>
                                                <p>New预览编辑</p>
                                            </a>
                                        </li>
                                    </ul>
{#                            {% endif %}#}
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>日志管理
                                    <i class="right fa fa-angle-left"></i></p>
                            </a>
{#                            {% if user.is_superuser %}#}
                            <ul class="nav nav-treeview" style="display:block">
                                <li class="nav-item">
                                    <a href="{% url 'cms:demo_cms_address_ip' %}" class="nav-link">
                                        <i class="fa fa-copy nav-icon"></i>
                                        <p>查看人数</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'cms:demo_cms_manager_client' %}" class="nav-link">
                                        <i class="fa fa-copy nav-icon"></i>
                                        <p>用户管理</p>
                                    </a>
                                </li>
                            </ul>
                            <li class="nav-item">
                                <a href="{% url 'cms:course_cms_add' %}" class="nav-link">
                                    <i class="fa fa-copy nav-icon"></i>
                                    <p>课程管理</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'cms:write_cms_add' %}" class="nav-link">
                                    <i class="fa fa-copy nav-icon"></i>
                                    <p>Test</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'cms:staff' %}" class="nav-link">
                                    <i class="fa fa-copy nav-icon"></i>
                                    <p>员工管理</p>
                                </a>
                            </li>
{#                            {% endif %}#}
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <!--中间内容-->
        {% block content %}{% endblock content %}

    </div>



<!-- jQuery -->
{#<script src="{% static 'adminLTE/plugins/jquery/jquery.min.js' %}"></script>#}
<!-- Bootstrap 4 -->
<script src="{% static 'adminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminLTE/dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'adminLTE/dist/js/demo.js' %}"></script>
</body>
</html>

front/templates/cms/template.html
{% extends 'cms/base.html' %}

{% block title %}{% endblock title %}

{% block style %}{% endblock style %}

{% block content %}
    <div class="content-wrapper" style="min-height:813px">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <h1>标题</h1>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    内容
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock content %}