apps/cms/urls.py
from django.urls import path
from . import views,views_of_course,views_of_staff
from django.conf.urls.static import static
from django.conf import settings
app_name = 'cms'
urlpatterns = [
    path('home',views.home,name = 'home'),
    path('news_release',views.news_release,name = 'news_release'),
    path('release_news',views.ReleaseNews.as_view(),name = 'release_news'),
    path('category',views.category,name = 'category'),
    path('image_upload_to_local',views.image_upload_to_local,name = 'image_upload_to_local'),
    path('category_modify',views.category_modify,name = 'category_modify'),
    path('category_delete',views.category_delete,name = 'category_delete'),
    path('thumbnail_process',views.thumbnail_process,name = 'thumbnail_process'),
    path('banner_control',views.banner_control,name = 'banner_control'),
    path('banner_cms_manager_get', views.banner_cms_manager_get, name='banner_cms_manager_get'),
    path('banner_cms_manager_add', views.banner_cms_manager_add, name='banner_cms_manager_add'),
    path('banner_cms_manager_edit', views.banner_cms_manager_edit, name='banner_cms_manager_edit'),
    path('banner_cms_manager_delete', views.banner_cms_manager_delete, name='banner_cms_manager_delete'),
    path('lover_mumu', views.lover_mumu, name='lover_mumu'),
    path('Discover_Process', views.Discover_Process, name='Discover_Process'),
    path('demo_cms_address_ip', views.demo_cms_address_ip, name='demo_cms_address_ip'),
    path('demo_cms_manager_client', views.demo_cms_manager_client, name='demo_cms_manager_client'),
    path('demo_cms_delete_ip', views.demo_cms_delete_ip, name='demo_cms_delete_ip'),
    path('news_preview_cms_all', views.News_preview_cms_all.as_view(), name='news_preview_cms_all'),
    path('news_preview_cms_edit', views.news_preview_cms_edit, name='news_preview_cms_edit'),
    path('news_preview_cms_delete', views.news_preview_cms_delete, name='news_preview_cms_delete'),
]+static(settings.CLIENTIMAGE_ROOT,document_root = settings.CLIENTIMAGE_ROOT)


urlpatterns += [
    path('course_cms_add',views_of_course.PublishCourse.as_view(),name='course_cms_add'),
    path('write_cms_add',views_of_course.write_cms_add,name='write_cms_add'),
]


#管理员
urlpatterns += [
    path('staff',views_of_staff.staff,name='staff'),
    path('StaffAdd',views_of_staff.StaffAdd.as_view(),name='StaffAdd'),
]

xfz02/urls.py
from django.contrib import admin
from django.urls import path,include
from apps.news import views
from apps.legend import views as views_legend
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/',include('apps.news.urls')),
    path('',views.index,name='index'),
    path('cms/',include('apps.cms.urls')),
    path('register/',include('apps.register.urls')),
    path('course/',include('apps.course.urls')),
    path('pay/',include('apps.payinfo.urls')),
    path('search/',include('apps.search.urls')),
    path('ueditor/',include('apps.ueditor.urls')),
    path('party/',include('apps.party.urls')),
    path('legend',views_legend.index),
    path('legend',include('apps.legend.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

apps/cms/models.py
from django.db import models

# Create your models here.

class Address(models.Model):
    ip = models.CharField(max_length=20)
    content = models.CharField(max_length=20,default='null')
    country = models.CharField(max_length=10,default='null')
    province = models.CharField(max_length=10,default='null')
    city = models.CharField(max_length=10,default='null')
    isp = models.CharField(max_length=10,default='null')
    pub_time = models.DateTimeField(auto_now_add='null')
    class Meta:
        ordering =['-pub_time']

apps/cms/forms.py
from django import forms
from utils.restful import FormError
from utils import restful
from apps.course.models import Course
from apps.news.models import News,Banner


class NewsForm(forms.ModelForm,FormError):
    category = forms.IntegerField()
    class Meta:
        model = News
        fields = ('title','content','thumbnail')



class CategoryForm(forms.Form,FormError):
    id = forms.CharField(max_length=20,required=False)
    name = forms.CharField(max_length=30)


class BannerForm(forms.ModelForm,FormError):
    banner_id = forms.IntegerField(required=False)
    class Meta:
        model = Banner
        fields = '__all__'

class PubCourseForm(forms.ModelForm,FormError):
    category_id = forms.IntegerField()
    teacher_id = forms.IntegerField()
    class Meta:
        model = Course
        exclude = ("category",'teacher')

apps/cms/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View
from utils import restful
from .forms import CategoryForm,NewsForm,BannerForm
from apps.news.models import Category,Banner,News,Discover
import os,time
from django.conf import settings
from qiniu import Auth as qiniuAuth
from apps.news.serializers import BannerSerializers
from apps.news.forms import DiscoverForm
from apps.register.models import User
from .models import Address
from django.utils.timezone import make_aware
from datetime import datetime
from django.core.paginator import Paginator
from urllib import parse

#权限访问装饰器
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required
from django.contrib.admin.views.decorators import staff_member_required

# Create your views here.
def home(request):
    return render(request, 'cms/news/home.html')


@staff_member_required(login_url='index')
def news_release(request):
    return render(request,'cms/news/release.html')


#发布新闻
@method_decorator(permission_required(perm='news.add_news',login_url='/'),name='dispatch')
class ReleaseNews(View):
    def get(self,request):
        category = Category.objects.all()
        context = {'category':category}
        return render(request,'cms/news/release.html',context=context)
    def post(self,request):
        print('到post这了')
        form = NewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            print('content',content)
            category_id = form.cleaned_data.get('category')
            category = Category.objects.get(id = category_id)
            print('category_id',category_id)
            thumbnail = form.cleaned_data.get('thumbnail')
            author = request.user
            new = News.objects.create(title=title,content=content,category=category,thumbnail=thumbnail,author=author)
            new.save()
            print('OK')
            return restful.ok()
        print('表单错')
        print('form.get_errors',form.get_errors)
        return restful.params_error(message='表单提交有问题')
#标签


def category(request):
    if request.method == 'GET':
        categorys = Category.objects.prefetch_related('news_set').all().order_by("-id")
        content = {'categorys':categorys}
        return render(request,'cms/news/category.html',context=content)
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            print('name',name)
            category = Category.objects.create(name=name)
            category.save()
            return restful.result(message='添加成功')
        return restful.params_error('表单验证错误')


def image_upload_to_local(request):
    file = request.FILES.get('file')
    file_name = file.name.split('.')[1]
    file_name = str(int(time.time()*1000))+ '.' +file_name
    with open((os.path.join(settings.CLIENTIMAGE_ROOT,file_name)),'wb') as f:
        for chunk in file.chunks():
            f.write(chunk)
    url = request.build_absolute_uri(settings.STATIC_URL+'client_image/'+file_name)
    print(url)
    return restful.result(data={'url':url})

@method_decorator(permission_required(perm='category.change_category',login_url='/'),name='dispatch')
def category_modify(request):
    form = CategoryForm(request.POST)
    if form.is_valid():
        id = form.cleaned_data.get('id')
        print('category_id',id)
        name = form.cleaned_data.get('name')
        print('category_name',name)
        try:
            Category.objects.filter(pk=id).update(name=name)
            return restful.ok()
        except:
            return restful.params_error('该分类不存在')

    else:
        return restful.params_error(message=form.get_error())

@method_decorator(permission_required(perm='category.delete_category',login_url='/'),name='dispatch')
def category_delete(request):
    id = request.POST.get('id')
    print('id',id)
    if id:
        try:
            dele = Category.objects.filter(id=id).delete()
            print('dele',dele)
            return restful.ok()
        except:
            return  restful.params_error(message='数据库无法查到这个ID，请刷新')
    else:
        return restful.params_error(message='没有这个名称，无法删除，请刷新')


def thumbnail_process(request):
    access_key = 'L7Idi7_0oH-8LC1g2CjLb1h9Z6kN4-JLoqoOn21U'
    secret_key = 'IGhDFYcbCns_3RcEopOwmHLE8M7XctIe_bVwYfHr'
    bucket = 'establish'
    q = qiniuAuth(access_key,secret_key)
    token = q.upload_token(bucket)
    return restful.result(data={'token':token})

def banner_control(request):
    return render(request,'cms/banner/banner.html')


#管理banner
def banner_cms_manager_get(request):
    banner = Banner.objects.all()
    serializer = BannerSerializers(banner,many=True).data
    context = {'banners':serializer}
    return restful.result(data=context)

#添加banner

def banner_cms_manager_add(request):
    form = BannerForm(request.POST)
    if form.is_valid():
        link_to = form.cleaned_data.get('link_to')
        priority = form.cleaned_data.get('priority')
        image_url = form.cleaned_data.get('image_url')
        banner = Banner.objects.create(link_to=link_to,priority=priority,image_url=image_url)
        banner.save()
        return restful.result(data={'banner_id':banner.id})
    else:
        return restful.params_error(form.get_errors())

#删除banner
def banner_cms_manager_delete(request):
    banner_id = request.POST.get('banner_id')
    print('banner_id_POST',banner_id)
    banner_id_get = request.GET.get('banner_id')
    print('banner_id_GET',banner_id_get)
    try:
        banner = Banner.objects.get(id=banner_id).delete()
        return restful.ok()
    except:
        return  restful.params_error(message='没有这条数据,请刷新')


#编辑banner
def banner_cms_manager_edit(request):
    form = BannerForm(request.POST)
    if form.is_valid():
        link_to = form.cleaned_data.get('link_to')
        priority = form.cleaned_data.get('priority')
        image_url = form.cleaned_data.get('image_url')
        banner_id = form.cleaned_data.get('banner_id')
        banner = Banner.objects.filter(id=banner_id)
        banner.update(link_to=link_to,priority=priority,image_url=image_url)
        return restful.ok()
    else:
        return restful.params_error(message=form.get_errors())



#慕慕
def lover_mumu(request):
    restful.get_address_by_138ip(request,'慕慕blog访问')
    return render(request,'cms/banner/mumu.html')


#主页留言版
def Discover_Process(request):
    count = settings.PAGE_LOAD_NUM
    if request.method == 'GET':
        pp = restful.get_address_by_138ip(request=request)
        print(pp)
        discover = Discover.objects.all().select_related('author')
        context = {'discover': discover}
        return render(request, 'news/discover.html', context)
    else:
        form = DiscoverForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data.get('content')
            if str(request.user) != 'AnonymousUser':
                author = request.user
            else:
                exist = User.objects.filter(username='还未注册用户1').exists()
                if exist:
                    author = User.objects.get(username='还未注册用户1')
                else:
                    author = User.objects.create_user(username='还未注册用户1', password=12341234, telephone=13005611199,
                                                      is_staff=0)
            disc = Discover.objects.create(content=content, author=author)
            disc.save()
            return restful.ok()
        else:
            return restful.params_error('内容或标题不能为空')

#渲染IP页面
def demo_cms_address_ip(request):
    address = Address.objects.all()
    return render(request,'cms/demo/address.html',context={'addresses':address})


#查用户
def demo_cms_manager_client(request):
    user = User.objects.all()
    return render(request,'cms/demo/user_manager.html',context={'users':user})

#删除IP
def demo_cms_delete_ip(request):
    pk = request.POST.get('pk')
    try:
        Address.objects.get(pk=pk).delete()
        return restful.ok()
    except :
        return restful.params_error('未查到该id')

#新闻列表遍历
class News_preview_cms_all(View):
    def get(self,request):
        start = request.GET.get('start')
        end = request.GET.get('end')
        category = int(request.GET.get('category',0) or 0)
        title = request.GET.get('news-title')
        content = request.GET.get('news-content')
        p_for_web = request.GET.get('p_for_web',1)
        print('start',start)
        print('end',end)
        print('title', title)
        print('content', content)
        print('category', category)

        newses = News.objects.select_related('category','author').all()

        if start or end:
            if start:
                try :
                    start = make_aware(datetime.strptime(start, '%Y/%m/%d'))
                    print('start', start)
                except ValueError :
                    start = start
            else:
                start = datetime(year=2019, month=5, day=1)
                print('start', start)
            if end:
                try:
                    end = make_aware(datetime.strptime(end, '%Y/%m/%d'))
                except ValueError :
                    end = end
            else:
                end = datetime.now()
                print('end', end)
            newses = newses.filter(pub_time__range=(start, end))
        if category:
            newses = newses.filter(category=category)
        if title:
            newses = newses.filter(title__icontains=title)
        if content:
            newses = newses.filter(content__icontains=content)

        #&start=20121111&start=20121112
        urlencode = '&' + parse.urlencode({'start': start or '',
                                           'end': end or '',

front/templates/cms/staff/addstaff.html
{% extends 'cms/base.html' %}

{% block title %}{% endblock title %}

{% block style %}{% endblock style %}

{% block content %}
    <div class="content-wrapper" style="min-height:813px">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <h1>添加权限</h1>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <form class="form-group col-4" method="post">
                        {% csrf_token %}
                        <label for="form-username"><h4>用户名</h4></label>
                        <input type="text" name="username" class="form-control" id="form-username" />
                        <div style="margin-left: 20px">
                            {% for group in groups %}
                                <div style="margin-right: 30px;float:left;">
                                    <label for="group-box-{{ group.pk }}"><h5>{{ group.name }}</h5></label>
                                    <input type="checkbox" value="{{ group.pk }}" id="group-box-{{ group.pk }}" name="groups" />
                                </div>
                            {% endfor %}
                        </div>

                        <button class="btn btn-primary">提交</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock content %}

front/templates/cms/staff/staff.html
{% extends 'cms/base.html' %}
{% load news_utils %}
{% block title %}{% endblock title %}

{% block style %}{% endblock style %}

{% block content %}
    <div class="content-wrapper" style="min-height:813px">
        <section class="content-header" >
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        员人管理
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <table class="table table-bordered">
                            <thead>
                                <tr >
                                    <th>用户名</th>
                                    <th>手机</th>
                                    <th>加入时间</th>
                                    <th>权限组</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for staff in staffs %}
                                <tr>
                                    <td>{{ staff.username }}</td>
                                    <td>{{ staff.telephone }}</td>
                                    <td>{{ staff.joined_time|time_since }}</td>
                                    {% if staff.is_superuser %}
                                        <td>超级管理员</td>
                                    {% else %}
                                        <td>
                                            {% for group in staff.groups.all %}
                                                {{ group.name }}
                                            {% endfor %}
                                        </td>
                                    {% endif %}


                                    <td>
                                        <a href="{% url 'cms:StaffAdd' %}" class="btn btn-primary">添加权限</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock content %}