apps/cms/urls.py
from django.urls import path
from . import views,views_of_course,views_of_staff
from django.conf.urls.static import static
from django.conf import settings
app_name = 'cms'
urlpatterns = [
    path('home',views.home,name = 'home'),
    path('news_release',views.news_release,name = 'news_release'),
    path('release_news',views.ReleaseNews.as_view(),name = 'release_news'),
    path('category',views.category,name = 'category'),
    path('image_upload_to_local',views.image_upload_to_local,name = 'image_upload_to_local'),
    path('category_modify',views.category_modify,name = 'category_modify'),
    path('category_delete',views.category_delete,name = 'category_delete'),
    path('thumbnail_process',views.thumbnail_process,name = 'thumbnail_process'),
    path('banner_control',views.banner_control,name = 'banner_control'),
    path('banner_cms_manager_get', views.banner_cms_manager_get, name='banner_cms_manager_get'),
    path('banner_cms_manager_add', views.banner_cms_manager_add, name='banner_cms_manager_add'),
    path('banner_cms_manager_edit', views.banner_cms_manager_edit, name='banner_cms_manager_edit'),
    path('banner_cms_manager_delete', views.banner_cms_manager_delete, name='banner_cms_manager_delete'),
    path('lover_mumu', views.lover_mumu, name='lover_mumu'),
    path('Discover_Process', views.Discover_Process, name='Discover_Process'),
    path('demo_cms_address_ip', views.demo_cms_address_ip, name='demo_cms_address_ip'),
    path('demo_cms_manager_client', views.demo_cms_manager_client, name='demo_cms_manager_client'),
    path('demo_cms_delete_ip', views.demo_cms_delete_ip, name='demo_cms_delete_ip'),
    path('news_preview_cms_all', views.News_preview_cms_all.as_view(), name='news_preview_cms_all'),
    path('news_preview_cms_edit', views.news_preview_cms_edit, name='news_preview_cms_edit'),
    path('news_preview_cms_delete', views.news_preview_cms_delete, name='news_preview_cms_delete'),
]+static(settings.CLIENTIMAGE_ROOT,document_root = settings.CLIENTIMAGE_ROOT)


urlpatterns += [
    path('course_cms_add',views_of_course.PublishCourse.as_view(),name='course_cms_add'),
    path('write_cms_add',views_of_course.write_cms_add,name='write_cms_add'),
]


#管理员
urlpatterns += [
    path('staff',views_of_staff.staff,name='staff'),
    path('StaffAdd',views_of_staff.StaffAdd.as_view(),name='StaffAdd'),
]

apps/course/urls.py
from django.urls import path
from . import views
app_name = 'course'
urlpatterns = [
    path('index',views.course_index,name ='index'),
    path('detail',views.course_detail,name = 'detail'),
    path('course_detail/<int:course_id>',views.course_detail,name = 'course_detail'),
    path('course_token',views.course_token,name = 'course_token'),
    path('course_order_key',views.course_order_key,name = 'course_order_key'),
    path('notify_view',views.notify_view,name = 'notify_view'),
    path('course_pay/<int:course_id>',views.course_pay,name = 'course_pay'),
    path('login_requireds',views.login_requireds,name = 'login_requireds'),
]

apps/news/urls.py
from django.urls import path
from .import views

app_name = 'news'
urlpatterns = [
    path('index',views.index,name='index'),
    path('news_list',views.news_list,name='news_list'),
    path('news_detail/<int:news_id>',views.news_detail,name='news_detail'),
    path('news_comment',views.news_comment,name='news_comment'),

]

apps/register/urls.py
from django.urls import path
from . import views
app_name = 'register'
urlpatterns = [
    path('loginView',views.loginView,name = 'loginView'),
    path('loginrequire',views.loginrequire,name='loginrequire'),
    path('signupView',views.signupView,name='signupView'),
    path('logoutView',views.logOutView,name='logoutView'),
    path('img_captcha/',views.img_captcha,name='img_captcha'),
    path('test2',views.test2,name='test2'),
    path('send',views.send,name='send'),
    path('index',views.index,name='index'),
]

apps/search/urls.py
from django.urls import path,include
from . import views
app_name = 'search'
urlpatterns = [
    # path('index',include('haystack.urls'),name='index'),
    path('index',views.SearchPagi.as_view(),name='index'),
]

xfz02/urls.py
from django.contrib import admin
from django.urls import path,include
from apps.news import views
from apps.legend import views as views_legend
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/',include('apps.news.urls')),
    path('',views.index,name='index'),
    path('cms/',include('apps.cms.urls')),
    path('register/',include('apps.register.urls')),
    path('course/',include('apps.course.urls')),
    path('pay/',include('apps.payinfo.urls')),
    path('search/',include('apps.search.urls')),
    path('ueditor/',include('apps.ueditor.urls')),
    path('party/',include('apps.party.urls')),
    path('legend',views_legend.index),
    path('legend',include('apps.legend.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

apps/news/models.py
from django.db import models

# Create your models here.
class News(models.Model):
    title = models.CharField(max_length = 200)
    thumbnail = models.URLField()
    content = models.TextField()
    category = models.ForeignKey('Category',on_delete=models.SET_NULL,null=True)
    pub_time = models.DateTimeField(auto_now_add = True)
    author = models.ForeignKey('register.User',on_delete=models.SET_NULL,null= True)
    class Meta:
        ordering = ['-pub_time']

class Category(models.Model):
    name = models.CharField(max_length = 20)
    pub_time2 = models.DateTimeField(auto_now_add=True,null=True)


class Discover(models.Model):
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('register.User',on_delete=models.SET_NULL,null=True)

class NewsComment(models.Model):
    news = models.ForeignKey('News',on_delete=models.CASCADE,null=True,related_name='newscomment')
    comment = models.TextField(max_length=200)
    pub_time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('register.User',on_delete=models.SET_NULL,null=True)
    class Meta:
        ordering = ['-pub_time']


class Banner(models.Model):
    link_to = models.CharField(max_length=300)
    priority = models.IntegerField()
    image_url = models.URLField()
    pub_time = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-priority']

apps/news/forms.py
from django import forms
from .models import Discover,NewsComment,Banner
from utils.restful import FormError
from .formErrors import FormMixin2
class DiscoverForm(forms.ModelForm):
    class Meta:
        model = Discover
        exclude = ['pub_time','author']


class CommentForm(forms.ModelForm,FormError):
    class Meta:
        model = NewsComment
        exclude = ['author']
        error_messages = {
            'comment':{
                'max_length':'不能大于10个字符',
                'required': '内容不能为空哦'
            },
        }

apps/news/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from apps.news.models import News,NewsComment,Banner
from apps.news.forms import CommentForm
from utils import restful
from apps.register.models import User
from django.conf import settings
from .serializers import NewsSerializers,NewDetailSerializers,CommentSerializers,BannerSerializers


# Create your views here.



def index(request):
    newses = News.objects.all()[0:settings.PAGE_LOAD_NUM]
    banners = Banner.objects.all()
    context = {'newses':newses,'banners':banners}
    restful.get_address_by_138ip(request=request,content='进入到主页')
    return render(request,'news/index.html',context)

def news_list(request):
    num = 1
    p = int(request.GET.get('p',1))
    print('p',p)
    start = (p-1) * settings.PAGE_LOAD_NUM
    end = p * settings.PAGE_LOAD_NUM
    newes = News.objects.order_by('-pub_time')[start:end]
    num += 1
    serializers = NewsSerializers(newes,many=True).data
    content = {'news':serializers}
    return restful.result(data=content)

# def news_detail(request,news_id):
#     category_id = request.GET.get('category_id')
#     news = News.objects.select_related('author','category').get(id=news_id)
#     print('=*10'+'\n')
#     print('=*10'+'\n')
#     context = {'news':news}
#     return render(request,'news/news_detail.html',context = context)

def news_detail(request,news_id):
    category_id = request.GET.get('category_id')
    news = News.objects.prefetch_related('newscomment','author','category').get(id=news_id)
    print('='*10+'\n')
    for i in news.newscomment.all():
        print(i.comment)
    print('='*10+'\n')
    context = {'news':news}
    return render(request,'news/news_detail.html',context = context)

def news_comment(request):
    form = CommentForm(request.POST)
    if form.is_valid():
        news = form.cleaned_data.get('news')
        comment = form.cleaned_data.get('comment')
        if str(request.user) == 'AnonymousUser':
            author = User.objects.get(uid='123123')
        else:
            author = request.user
        print('author',author)
        comments = NewsComment.objects.create(news=news,comment=comment,author=author)
        comments.save()
        data = NewDetailSerializers(comments).data
        print('comments',comments)
        return restful.result(data=data)
    else:
        print('form.get_errors()走到这：',form.get_errors())
        return restful.params_error(form.get_errors())#get_errors()忘记加'()'错过一次

front/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>知了课堂</title>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
{#    <link rel="stylesheet" href="{% static 'css/news/index.min.css' %}">#}
{#    <script src="{% static 'js/signup_ajax_process.js' %}"></script>#}

    <script src="{% static 'js/login_ajax_process.js' %}"></script>
    <script src="{% static 'js/login_ajax.js' %}"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
    <link  rel="stylesheet" href="//at.alicdn.com/t/font_1516551_rvwqjg5f6hi.css">
    {#注册#}
    <link rel="stylesheet" href="{% static 'css/register/constants.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/register/init.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/register/login.min.css' %}">
    {% block header %}{% endblock header %}
</head>
<body>
{% block banner %}{% endblock banner %}
    <header class="header">
        <div class="container">
{#            <div class="logo-box">#}
{#                <a href="/"></a>#}
{#            </div>#}
            <ul class="nav" id="nav-ul-bar">
                <li><a href="{% url 'news:index' %}">首页</a></li>
                <li><a href="{% url 'course:index' %}">电影院</a></li>
                <li><a href="{% url 'search:index' %}">搜索</a></li>
                <li><a href="{% url 'cms:Discover_Process' %}">留言板块</a></li>
            </ul>

            <div class="auth-box">
                {% if user.is_authenticated %}
                    <ul class="auth-box-ul">
                        <li class="auth-box-li"><i class="icon-person iconfont "></i></li>
                        <li class="auth-box-li"><p>{{ user.username }}</p></li>
                    </ul>

                    <ul class="auth-more-box" >
                        <li class="group-triangel"><i class="icon-triangle iconfont"></i></li>
                        {% if user.is_staff %}
                            <li><a href="{% url 'cms:home' %}" class="personal-profile1">后台管理</a></li>
                        {% endif %}
                        <li><a href="#" class="'history">历史记录</a></li>
                        <li><a href="{% url 'register:logoutView' %}" class="'log-out-now" >退出</a></li>
                </ul>
                {% else %}
                    <i class="icon-person iconfont "></i>
                    <a href="#" class="login-text">登录</a> /
                    <a href="#" class="signup-text">注册</a>
                {% endif %}
            </div>
        </div>
    </header>



    {#注册登录模块#}
    <div class="main-login-test">
        <button type="button" class="button2-test" >退出</button>
        <div class="wrapper-test">
            <div class="top-test"></div>
            <div class="middle-test">
                <div class="movingBox1-test movingBox-test"></div>
                <div class="movingBox2-test movingBox-test"></div>
            </div>
        </div>
    </div>

{% block body %}{% endblock body %}

<br><br><br><br><br><br><br><br><br><br>


{#footer#}
{% block footer %}{% endblock footer %}
    <footer class="footer">
    <div class="top-group">
        <div class="top-inner-group">
            <div class="logo-box"></div>
            <div class="detail-group">
                <div class="line1">
                    <ul class="links">
                        <li><a href="/news/index">关于我</a></li>
                        <li><a href="/course/index">电影院</a></li>
                        <li><a href="/search/index">搜索</a></li>
                        <li><a href="/cms/Discover_Process">留言给我</a></li>
                    </ul>
                    <div class="about-us">
                        <span class="title">关于我们：</span>
                        <ul class="social-group">
                            <li class="weixin">
                                <div class="wx-qrcode"></div>
                                <span class="text">xfz008
                                </span>
                            </li>
                            <li class="weibo">
                                <a class="text" href="#">欢子个人博客</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="line2">
                    <p class="address">地址：广东省廉江市水流村101号</p>
                    <p class="contact">联系方式：13005611192（工作日8点半-18点）</p>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom-group">
        ©2019 欢子个人博客 粤ICP备15051289号-1
    </div>
</footer>




<div class="mask-wrapper">
    <div class="auth-wrapper">
        <div class="close-wrapper">
            <span class="close-btn icon-close1 iconfont"></span>
        </div>
        <div class="auth-inner-wrapper">
            <div class="scroll-wrapper">
                <div class="signin-group auth-group">
                    <span class="prompt-account">测试</span><br/>
                    <span class="prompt-password"></span>
                    <div class="top-group">
                        <span class="title">请登录</span>
                        <a href="javascript: void(0);" class="switch">立即注册></a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" name="username" placeholder="请输入手机号码或帐号">
                        </div>
                        <div class="input-group">
                            <input type="password" class="form-control" name="password" placeholder="请输入密码">
                        </div>
                        <div class="input-group">
                            <label class="remember-label">
                                <input type="checkbox" name="remember" value="1">
                                记住我
                            </label>
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn" id="signin-submit-btn" value="立即登录">
                        </div>
                    </div>
                </div>
                <div class="signup-group auth-group">
                    <div class="top-group">
                        <span class="title">请注册</span>
                        <a href="javascript: void(0);" class="switch">立即登录></a>
                    </div>
                    <form action="#" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="用户名">
                            </div>

                            <div class="input-group">
                                <input type="password" class="form-control" name="password1" placeholder="密码">
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password2" placeholder="确认密码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group img-captcha-group">
                                    <input type="text" class="form-control" name="img-captcha-code" placeholder="图形验证码">
                                </div>
                                <div class="input-group-addon">
                                    <img src="{% url 'register:img_captcha' %}" alt="" class="img-captcha" name="img-captcha-img" style="cursor:pointer;">
                                </div>
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                                </div>
                                <div class="input-group-addon">
                                    <span class="sms-captcha-btn">发送验证码</span>
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" id="signup-submit-btn" value="立即注册">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

front/templates/news/discover.html
{% extends 'news/base.html' %}
{% load news_utils %}
{% block header %}

{% endblock header %}

{% block body %}
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/news/discover.min.css' %}">
    <script src="{% static 'ueditor/ueditor.config.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.all.min.js' %}"></script>
    <script src="{% static 'js/discover/discover.js' %}"></script>
    <div class="container">
        <div class="leaveMessage">
            {% for disc in discover %}
                <div class="list-group-item active">
                    {% if disc.author %}
                        {{ disc.author }}
                    {% else %}
                        <a href="{% url 'register:signupView' %}">未登录用户</a>
                    {% endif %}
                </div>
                <div class="list-group-item list-group-item-success">
                    {{ disc.content|safe }}
                    time:{{ disc.pub_time|time_since }}
                </div>
                <br>
                <br>
            {% endfor %}
        </div>

        <form action="#">
            <ul class="ul-content">
                <li>
                    <label for="form-content">留言内容</label>
                    <script id="editor" type="text/plain"></script>
                </li>
                <li class="col-2 ">
                    <button class="btn btn-primary" id="btn-discover">提交</button>
                </li>
            </ul>
        </form>
    </div>
{% endblock body %}

front/templates/news/index.html
{% extends 'news/base.html' %}
{% load news_utils %}

{% block header %}
    <script src="{% static 'js/template-web.js' %}"></script>
    <script src="{% static 'js/news.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
{% endblock header %}

{% block body %}

<div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="banner-group" id="banner-group">
                    <ul class="banner-ul" id="banner-ul">
                        {% for banner in banners%}
                        <li>
                            <a href="#">
                                <img src="{{ banner.image_url }}" alt="">
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                    <span class="arrow left-arrow">‹</span>
                    <span class="arrow right-arrow">›</span>
                    <div class="page-control-group">
                        <ul class="page-control">
                        </ul>
                    </div>
                </div>
                <div class="list-outer-group">
                    <ul class="list-tab" >
                        <li class="active"><a href="#">最新资讯</a></li>
                    </ul>
                    <ul class="list-inner-group" >
                        {% for value in newses %}
                            <li>
                                <div class="thumbnail-group">
                                    <a href="#">
                                        <img src="{{ value.thumbnail }}" alt="">
                                    </a>
                                </div>
                                <div class="news-group">
                                    <p class="title">
                                        <a href="/news/news_detail/{{ value.id }}">{{ value.title }}</a>
                                    </p>
                                    <p class="desc">
                                        点击上方标签查看详细内容
                                    </p>
                                    <p class="more">
                                        <span class="category">{{ value.category.name }}</span>
                                        <span class="pub-time">{{ value.pub_time|time_since }}</span>
                                        <span class="author">{{ value.author.username }}</span>
                                    </p>
                                </div>
                            </li>
                        {% endfor %}
                        <script id="template_each" type="text/html">
                            {% verbatim %}
                                {{ each newses value num }}

                                    <li>
                                        <div class="thumbnail-group">
                                            <a href="#">
                                                <a href="/news/news_detail/{{ value.id }}"><img src="{{ value.thumbnail }}" alt=""></a>
                                            </a>
                                        </div>
                                        <div class="news-group">
                                            <p class="title">
                                                <a href="/news/news_detail/{{ value.id }}">{{ value.title }}</a>
                                            </p>
                                            <p class="desc">
                                                点击上方标签查看详细内容
                                            </p>
                                            <p class="more">
                                                <span class="category">{{ value.category.name }}</span>
                                                <span class="pub-time">{{ value.pub_time|time_since }}</span>
                                                <span class="author">{{ value.author.username }}</span>
                                            </p>
                                        </div>
                                    </li>
                                {{ /each }}
                            {% endverbatim %}
                        </script>
                    </ul>
                    <div class="load-more-group">
                        <button class="load-more" id="load-more-btn">查看更多</button>
                    </div>
                </div>
            </div>
{#            侧边栏#}
{#            <div class="sidebar-wrapper">#}
{#                <div class="title-group">#}
{#                    <span class="title">在线课堂</span>#}
{#                    <a class="more" href="#">更多</a>#}
{#                </div>#}
{#                <div class="advertise-group">#}
{#                    <a href="#">#}
{#                        <img src="http://www.xfz.cn/static/build/images/side-gift-banner.png" alt="">#}
{#                    </a>#}
{#                </div>#}
{#                <div class="platform-group">#}
{#                    <div class="title-group">#}
{#                        <span class="title">关注小饭桌</span>#}
{#                    </div>#}
{#                    <div class="focus-group">#}
{#                        <ul class="left-group">#}
{#                           <li class="zhihu">#}
{#                               <a href="#" target="_blank">小饭桌创业课堂</a>#}
{#                           </li>#}
{#                            <li class="weibo">#}
{#                               <a href="#" target="_blank">小饭桌创业课堂</a>#}
{#                           </li>#}
{#                            <li class="toutiao">#}
{#                               <a href="#" target="_blank">小饭桌</a>#}
{#                           </li>#}
{#                        </ul>#}
{#                        <div class="right-group">#}
{#                            <p class="desc">扫码关注小饭桌微信公众平台xfz008</p>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="hot-news-group">#}
{#                    <div class="title-group">#}
{#                        <span class="title">热门推荐</span>#}
{#                    </div>#}
{#                    <ul class="hot-list-group">#}
{#                        <li>#}
{#                            <div class="left-group">#}
{#                                <p class="title">#}
{#                                    <a href="#"></a>#}
{#                                </p>#}
{#                                <p class="more">#}
{#                                    <span class="category">深度报道</span>#}
{#                                    <span class="pub-time">1小时前</span>#}
{#                                </p>#}
{#                            </div>#}
{#                            <div class="right-group">#}
{#                                <a href="#">#}
{#                                    <img src="http://static-image.xfz.cn/1516169692_914.jpg-website.news.list" alt="">#}
{#                                </a>#}
{#                            </div>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#            </div>#}
        </div>
    </div>
{% endblock %}