apps/party/urls.py
from django.urls import path
from .import views

app_name = 'party'
urlpatterns = [
    path('',views.index,name='index'),
    path('comment',views.comment,name='comment'),
    path('write',views.write,name='write'),
    path('delete',views.delete,name='delete'),
    path('edit',views.Edit.as_view(),name='edit'),
]

apps/register/urls.py
from django.urls import path
from . import views
app_name = 'register'
urlpatterns = [
    path('loginView',views.loginView,name = 'loginView'),
    path('loginrequire',views.loginrequire,name='loginrequire'),
    path('signupView',views.signupView,name='signupView'),
    path('logoutView',views.logOutView,name='logoutView'),
    path('img_captcha/',views.img_captcha,name='img_captcha'),
    path('test2',views.test2,name='test2'),
    path('send',views.send,name='send'),
    path('index',views.index,name='index'),
]

xfz02/urls.py
from django.contrib import admin
from django.urls import path,include
from apps.news import views
from apps.legend import views as views_legend
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/',include('apps.news.urls')),
    path('',views.index,name='index'),
    path('cms/',include('apps.cms.urls')),
    path('register/',include('apps.register.urls')),
    path('course/',include('apps.course.urls')),
    path('pay/',include('apps.payinfo.urls')),
    path('search/',include('apps.search.urls')),
    path('ueditor/',include('apps.ueditor.urls')),
    path('party/',include('apps.party.urls')),
    path('legend',views_legend.index),
    path('legend',include('apps.legend.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

apps/party/models.py
from django.db import models

# Create your models here.
class Party(models.Model):
    name = models.CharField(max_length=200,default='空')
    cellphone = models.CharField(max_length=200,default='空')
    memo = models.CharField(max_length=200,default='空')
    money = models.CharField(max_length=200,default='')

apps/party/views.py
from django.shortcuts import render
from .models import Party
from utils import restful
from django.views import View
from .serializers import PartySerializers

def index(request):
    party = Party.objects.all()
    count = party.count()
    return  render(request,'party/index.html',{'partys':party,'count':count})

def comment(request):
    return render(request,'party/comment.html')

def write(request):
    name = request.GET.get('name')
    memo = request.GET.get('memo')
    cellphone = request.GET.get('cellphone')
    print('name',name)
    exists=Party.objects.filter(name=name).exists()
    if exists:
        return restful.result(code=400,message='姓名已存在')
    else:
        party = Party.objects.create(name=name,memo=memo,cellphone=cellphone)
        return restful.ok()

def delete(request):
    print('到这了')
    id = request.GET.get('id')
    Party.objects.get(pk=id).delete()
    return restful.ok()

class Edit(View):
    def get(self,request):
        id = request.GET.get('id')
        print('get到这了',id)
        party = Party.objects.get(pk=id)
        party2 = PartySerializers(party).data
        return restful.result(data={'party':party2})
    def post(self,request):
        id = request.POST.get('id')
        cellphone = request.POST.get('cellphone')
        name = request.POST.get('name'or'')
        memo = request.POST.get('memo'or'')
        money = request.POST.get('money'or'')

        print('POST,id到了！！！！！', id)
        print('cellphone', cellphone)
        print('name', name)
        print('memo', memo)
        print('money', money)
        party = Party.objects.filter(pk = id)
        party.update(cellphone=cellphone,name=name,memo=memo,money=money)

        return restful.ok()

front/templates/party/base.html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<title>初三二班聚会报名</title>
<link rel="stylesheet" type="text/css" href="/static/party/css/reset.css"/>
<script type="text/javascript" src="/static/party/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/static/party/js/js_z.js"></script>
<link rel="stylesheet" type="text/css" href="/static/party/plugins/FlexSlider/flexslider.css">
<script type="text/javascript" src="/static/party/plugins/FlexSlider/jquery.flexslider.js"></script>
<!--3d滚动-->
<link rel="stylesheet" type="text/css" href="/static/party/plugins/3d_gd/css/style.css"><script type="text/javascript" src="/static/party/plugins/3d_gd/js/jquery.roundabout-1.0.min.js"></script>
<script type="text/javascript" src="/static/party/plugins/3d_gd/js/jquery.easing.1.3.js"></script>
<!--3d滚动-->
<script type="text/javascript" src="/static/party/js/main.js"></script>
<link rel="stylesheet" type="text/css" href="/static/party/css/thems.css">
<link rel="stylesheet" type="text/css" href="/static/party/css/responsive.css">

    <link  rel="stylesheet" href="//at.alicdn.com/t/font_1516551_rvwqjg5f6hi.css">
<link rel="stylesheet" type="text/css" href="/static/css/register/init.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/register/constants.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/register/login.min.css">



<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/login_ajax_process.js' %}"></script>
<script src="{% static 'js/login_ajax.js' %}"></script>
<script src="{% static 'js/ajax.js' %}"></script>
<script src="{% static 'js/message.js' %}"></script>
<script src="{% static 'js/party/index.js' %}"></script>




<script type="text/javascript">
$(document).ready(function(){
	$('#featured-area ul').roundabout({
		easing: 'easeOutInCirc',
		duration: 600
	});
});
$(window).load(function() {
  $('.flexslider').flexslider({
	animation: "slide"
  });
});
</script>
</head>


<style>
    .logo-title{
        font-size:40px;
        margin-top:10px;
    }
    .mask-wrapper{
        z-index: 999;
    }
</style>

<body class="i_body">
<!--头部-->
<div class="header">
	<div class="head_bg">&nbsp;</div>
    <div class="head clearfix">
        <div class="logo"><span class="logo-title">初三2班</span></div>
        <ul class="nav clearfix">
            <li class="now"><a href="{% url 'party:index' %}">首页<span>HOME</span></a></li>
            {% if user.is_authenticated %}
                <li><a href="#" class="login-text">{{ user.username }}<span>已登录</span></a></li>
            {% else %}
                <li><a href="#" class="login-text">登录<span>login</span></a></li>
            {% endif %}

        </ul>
        <div class="nav_m">
        	<span class="n_icon">&nbsp;</span>
            <ul>
                <li class="now"><a href="{% url 'party:index' %}">首页<span>HOME</span></a></li>
                {% if user.is_authenticated %}
                    <li><a href="#" class="login-text">{{ user.username }}<span>已登录</span></a></li>
                {% else %}
                    <li><a href="#" class="login-text">登录<span>login</span></a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
<!--头部-->
<!--幻灯片-->
{#<div class="banner">#}
{#	<div class="slider slider_pc">#}
{#        <div class="flexslider">#}
{#          <ul class="slides">#}
{#            <li>#}
{#                <img src="/static/party/upload/banner.jpg" alt="" />#}
{#            </li>#}
{#            <li>#}
{#                <img src="/static/party/upload/banner.jpg" alt="" />#}
{#            </li>#}
{#            <li>#}
{#                <img src="/static/party/upload/banner.jpg" alt="" />#}
{#            </li>#}
{#          </ul>#}
{#        </div>#}
{#    </div>#}
{#    <div class="slider slider_sj">#}
{#        <div class="flexslider">#}
{#          <ul class="slides">#}
{#            <li>#}
{#                <img src="/static/party/upload/shouji.jpg" alt="" />#}
{#            </li>#}
{#            <li>#}
{#                <img src="/static/party/upload/shouji.jpg" alt="" />#}
{#            </li>#}
{#            <li>#}
{#                <img src="/static/party/upload/shouji.jpg" alt="" />#}
{#            </li>#}
{#          </ul>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
<!--幻灯片-->

{% block content %}{% endblock %}






<div class="space_hx">&nbsp;</div>
<div class="bq">middle school © 2020</div>
<script language="javascript">
$(function(){
})
</script>



{#//登录#}
<div class="mask-wrapper mask-wrapper-show">
    <div class="auth-wrapper">
        <div class="close-wrapper">
            <span class="close-btn icon-close1 iconfont"></span>
        </div>
        <div class="auth-inner-wrapper">
            <div class="scroll-wrapper">
                <div class="signin-group auth-group">
                    <span class="prompt-account">测试</span><br/>
                    <span class="prompt-password"></span>
                    <div class="top-group">
                        <span class="title">请登录</span>
                        <a href="javascript: void(0);" class="switch">立即注册></a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" name="username" placeholder="请输入手机号码或帐号">
                        </div>
                        <div class="input-group">
                            <input type="password" class="form-control" name="password" placeholder="请输入密码">
                        </div>
                        <div class="input-group">
                            <label class="remember-label">
                                <input type="checkbox" name="remember" value="1">
                                记住我
                            </label>
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn" id="signin-submit-btn" value="立即登录">
                        </div>
                    </div>
                </div>
                <div class="signup-group auth-group">
                    <div class="top-group">
                        <span class="title">请注册</span>
                        <a href="javascript: void(0);" class="switch">立即登录></a>
                    </div>
                    <form action="#" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="用户名">
                            </div>

                            <div class="input-group">
                                <input type="password" class="form-control" name="password1" placeholder="密码">
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password2" placeholder="确认密码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group img-captcha-group">
                                    <input type="text" class="form-control" name="img-captcha-code" placeholder="图形验证码">
                                </div>
                                <div class="input-group-addon">
                                    <img src="{% url 'register:img_captcha' %}" alt="" class="img-captcha" name="img-captcha-img" style="cursor:pointer;">
                                </div>
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                                </div>
                                <div class="input-group-addon">
                                    <span class="sms-captcha-btn">发送验证码</span>
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn-party" id="signup-submit-btn" value="立即注册">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



</body>
</html>

front/templates/party/comment.html
{% extends 'party/base.html' %}

{% block content %}
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/news/discover.min.css' %}">
    <script src="{% static 'ueditor/ueditor.config.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.all.min.js' %}"></script>
    <script src="{% static 'js/discover/discover.js' %}"></script>
    <div class="container">
{#        <div class="leaveMessage">#}
{#            {% for disc in discover %}#}
{#                <div class="list-group-item active">#}
{#                    {% if disc.author %}#}
{#                        {{ disc.author }}#}
{#                    {% else %}#}
{#                        <a href="{% url 'register:signupView' %}">未登录用户</a>#}
{#                    {% endif %}#}
{#                </div>#}
{#                <div class="list-group-item list-group-item-success">#}
{#                    <span>2012</span>#}
{#                    {{ disc.content|safe }}#}
{#                    time:2012#}
{#                </div>#}
{#                <br>#}
{#                <br>#}
{#            {% endfor %}#}
{#        </div>#}
        <div class="leaveMessage">
                <div class="list-group-item active">
                未登录用户
                </div>
                <div class="list-group-item list-group-item-success">
                    <span>我留言了</span>
                    time:2012
                </div>
                <br>
                <br>
        </div>

        <form action="#">
            <ul class="ul-content">
                <li>
                    <label for="form-content">留言内容</label>
                    <script id="editor" type="text/plain"></script>
                </li>
                <li class="col-2 ">
                    <button class="btn btn-primary" id="btn-discover">提交</button>
                </li>
            </ul>
        </form>
    </div>
{% endblock %}

front/templates/party/index.html
{% extends 'party/base.html' %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/sweetalert/sweetalert.css' %}">
    <script src="{% static 'css/sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/alert.js' %}"></script>

<div class="i_box gy">
	<div class="title"><img src="/static/party/images/n_1.png" alt=""/></div>
    <div style="font-size:25px;color:white;">
        <div >时间：2020年1月25日晚(年初一)</div>
        <div>地址：待定</div>
        <div>组织人：梁宇进</div>
        <div>手机：13826480251</div>
    </div>

    <div class="gy_m">
    	  <div id="featured-area">
            <ul>
                <li><a href=""><img src="/static/party/upload/pic4.jpg" alt=""/></a></li>
            </ul>
        </div>
        <div class="gy_a"><span>{ 吃饭 }</span></div>
        <div class="gy_b">
            <div class="line">&nbsp;</div>
            <p>多年<br/>你还好吗</p>
        </div>
        <div class="gy_c">
            <div class="gy_cm">喝酒。</div>
        </div>
    </div>
</div>

<div class="jstore clearfix">
    <div class="left">
        <div >
            <a href="#" class="call-me-in"><img src="{% static 'party/images/call_me_in.png' %}" alt=""></a>
        </div>
    </div>
    <div class="right">
        <table class="table">
            <thead>
            <tr>
                <th>序列</th>
                <th>姓名</th>
                <th>手机</th>
                <th>备注</th>
                {% if user.username == '林朝欢' %}
                    <th>已收款</th>
                    <th>管理员操作</th>
                {% elif user.username == '梁宇进' %}
                    <th>已收款</th>
                    <th>管理员操作</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for party in partys %}
            <tr data-id="{{ party.pk }}">
                <td><em class="red">{{ forloop.counter }}</em></td>
                <td><em class="red">{{ party.name }}</em></td>
                <td><em class="red">{{ party.cellphone }}</em></td>
                <td><em class="red">{{ party.memo }}</em></td>
                {% if user.username == '林朝欢' %}
                    <td><em class="red">{{ party.money }}</em></td>
                    <td>
                        <button class="btn delete-partyname">删除</button>
                        <button class="btn edit-partyname">编辑</button>
                    </td>
                {% elif user.username == '梁宇进' %}
                    <td><em class="red">{{ party.money }}</em></td>
                    <td>
                        <button class="btn delete-partyname">删除</button>
                        <button class="btn edit-partyname">编辑</button>
                    </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    <span style="color:slateblue">共{{ count }}人</span>
    </div>
</div>

    <div class="slider">
        <div style="font-size:25px;color:white;">
            <div>费用：每人200</div>
        </div>
            <img src="{% static 'party/images/liangyujin.jpg' %}" alt="">
    </div>

<div class="mask-wrapper mask-wrapper2">
    <div class="auth-wrapper">
        <div class="close-wrapper">
            <span class="close-btn icon-close1 iconfont"></span>
        </div>
        <div class="auth-inner-wrapper">
            <div class="scroll-wrapper">
                <div class="signin-group auth-group">
                    <span class="prompt-account">测试</span><br/>
                    <span class="prompt-password"></span>
                    <div class="top-group">
                        <span class="title">请报名</span>
                    </div>
                    <div class="form-group party-memo">
                        <div class="input-group">
                            <input type="text" class="form-control" name="name" placeholder="姓名">
                        </div>
                        <div class="input-group">
                            <input type="text" class="form-control" name="cellphone" placeholder="手机号码">
                        </div>
                        <div class="input-group">
                            <input type="text" class="form-control" name="memo" placeholder="备注">
                        </div>
                        <div class="input-group">
                            {% if party %}
                            <input type="submit" class="submit-btn" id="submit-party" value="立即报名">
                            {% else %}
                            <input type="submit" class="submit-btn" id="submit-party" value="立即报名">
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{#    编辑#}
<div class="mask-wrapper mask-wrapper3">
    <div class="auth-wrapper">
        <div class="close-wrapper">
            <span class="close-btn icon-close1 iconfont"></span>
        </div>
        <div class="auth-inner-wrapper">
            <div class="scroll-wrapper">
                <div class="signin-group auth-group">
                    <span class="prompt-account">测试</span><br/>
                    <span class="prompt-password"></span>
                    <div class="top-group">
                        <span class="title">编辑</span>
                    </div>
                    <div class="form-group party-memo">
                        <div class="input-group">
                            <label>姓名</label>
                            <input type="text" class="form-control" name="name" placeholder="姓名">
                        </div>
                        <div class="input-group">
                            <label>手机号码</label>
                            <input type="text" class="form-control" name="cellphone" placeholder="手机号码">
                        </div>

                        <div class="input-group">
                            <label>已收款</label>
                            <input type="text" class="form-control" name="money" placeholder="">
                        </div>

                        <div class="input-group">
                            <label>备注</label>
                            <input type="text" class="form-control" name="memo" placeholder="备注">
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn" id="submit-party-edit" value="立即编辑">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>





<div class="space_hx">&nbsp;</div>
{#<div class="i_box lx">#}
{#	<div class="title"><img src="/static/party/images/n_5.png" alt=""/></div>#}
{#    <div class="lx_m clearfix">#}
{#    	<a href=""><img src="/static/party/images/icon6.png" alt=""/></a>#}
{#        <p>加盟热线：0755-82369636</p>#}
{#        <div class="if_nav">#}
{#        	<a href="">关于我们</a>#}
{#            <a href="">联系我们</a>#}
{#            <a href="">在线留言</a>#}
{#            <a href="">加入我们</a>#}
{#            <a href="">门店资讯</a>#}
{#        </div>#}
{#    </div>#}
{#</div>#}

{% endblock %}